### ISSUE TITLE
How to set creds for picobrew?

### ISSUE THREAD

**Issue by reaperharvest** [tmack8001/picobrew#1]
Hi, this is a cool project and needed now more than ever. I haven't been able to figure out how to set my pico creds for this cli to work. I see the credentials.ts file but not sure how to call it once the picobrew-cli is installed. Any help would be appreciated

**Comment by tmack8001** [comment]
When using the CLI it will ask for your "cookie" to authenticate temporarily against Picobrew (not your password). When entered for the first time this cookie is stored in what is known as the "key chain" within the operating system under the key "picobrew" for later reference when you run the CLI a second time.

Let me know if that answers your questions.

**Comment by chupalt** [comment]
I get the same behavior as @reaperharvest.  I never get a prompt for the cookie.  I'm on macOS Catalina 10.15.3.  Here is the trace from a recipe request.

% picobrew recipes ae49c28a88fa4da397d7acfe999d94cf
arguments received:  { recipeId: 'ae49c28a88fa4da397d7acfe999d94cf' }
flags received:  {
  format: 'beerxml',
  output_folder: 'recipes',
  all: false,
  verbose: false
}
pulling recipe ae49c28a88fa4da397d7acfe999d94cf from Picobrew's BrewHouse
TypeError: Cannot read property 'account' of undefined
    at credentials (/usr/local/lib/node_modules/picobrew-cli/lib/credentials.js:20:33)
    at async Recipes.run (/usr/local/lib/node_modules/picobrew-cli/lib/commands/recipes.js:20:39)
    at async Recipes._run (/usr/local/lib/node_modules/picobrew-cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/usr/local/lib/node_modules/picobrew-cli/node_modules/@oclif/config/lib/config.js:172:9)
    at async Main.run (/usr/local/lib/node_modules/picobrew-cli/node_modules/@oclif/command/lib/main.js:22:9)
    at async Main._run (/usr/local/lib/node_modules/picobrew-cli/node_modules/@oclif/command/lib/command.js:43:20)

**Comment by reaperharvest** [comment]
Yeah for me the cli never prompts me to enter a cookie or any other information related to authentication.

**Comment by tmack8001** [comment]
Interesting I must not handle the initial setup of the keychain correctly. I'll take a look at it, thanks for the detailed report.

**Comment by tmack8001** [comment]
> I get the same behavior as @reaperharvest. I never get a prompt for the cookie. I'm on macOS Catalina 10.15.3.

If you open "KeyChain" on your Mac and search for `picobrew` do you find any credentials? If so can you open the credential details and send me that information (obviously without the password prompt see below image).

If there is one then either a) you used this CLI and uploaded an invalid username+password combination, I should be better about cleaning and general error handling or b) another tool set this for you somehow.

![image](https://user-images.githubusercontent.com/2158627/84077159-e6322c80-a9a4-11ea-9154-2f1ee5a44228.png)

One thing you can try is delete the item that was there and see if that helps to resolve the situation. Maybe I should be using a keychain "service name" that is more explicitly matching to this tool... instead of a generic "picobrew" one.

**Comment by tmack8001** [comment]
Also what I'm storing as the "password" isn't actually the picobrew password... I could do that, but haven't found or tried to find a "login exchange" API. So right now just asking for the `.ASPXAUTH` cookie value and storing that, issue with that is it is "short" lived and thus needs to be refreshed every once and a while.

Today I noticed mine expired and now I'm getting this error without a native / build-in manner to clean the credentials leading me to the key chain to manually delete the credentials making the CLI request new pairs.

```
(node:59653) UnhandledPromiseRejectionWarning: HTTPError: Response code 403 (Forbidden)
    at PromisableRequest.<anonymous> (/Users/tmack/dev/projects/trevormack/picobrew/node_modules/got/dist/source/as-promise/index.js:124:28)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:59653) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:59653) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by tmack8001** [comment]
Here is an example interaction after I fixed some of the edge case handling today in the credentials.ts file.

```
./bin/run recipes 95bd40cc4f4a4843923f88128b2286a6 --verbose
arguments received:  { recipeId: '95bd40cc4f4a4843923f88128b2286a6' }
flags received:  {
  verbose: true,
  format: 'beerxml',
  output_folder: 'recipes',
  all: false
}

pulling recipe 95bd40cc4f4a4843923f88128b2286a6 from Picobrew's BrewHouse
What is your PicoBrew user identifier (ie. 28341)?: 28341
What is '.ASPXAUTH' cookie value?: ************************************************************************************************************************************************************************************************
writing file Slip O Sunnyshine.xml for recipe Slip O Sunnyshine
```
