### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by NCAvian** [tmack8001/picobrew#3]
I'm getting a syntax error when I try to run the code.  I installed npm, node.js, and libsecret-1-dev to satisfy the dependencies.  Compiled as root.  Fails on first run.  Any suggestions?

![image](https://user-images.githubusercontent.com/42758534/89092900-ae7fa980-d383-11ea-97d4-8c93cb487c93.png)

**Comment by tmack8001** [comment]
Interesting as I don't get that syntax error. What version of nodejs are you using? Looks like from the screenshot that the wanted version of nodejs is `>=10` but you are running `node: 8.10.0`

For instance here is my nodejs version:

```
$ node --version
v12.6.0
$ npm --version
6.14.6
```

Try to upgrade your nodejs installation to >=10 and see if the error continues.

**Comment by tmack8001** [comment]
I highly recommend https://github.com/nvm-sh/nvm for managing node versions across several projects.
